
export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpeg",
      username: " Arshad Alam",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpeg",
      username: "  Abhishek mishra",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpeg",
      username: "  Anshika mittal",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "  Milan chatterjee",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "  Naman jain",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: " Akash gangwar",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "  Pavan Chandana",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "  Toshik Rathore",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "  Ishan Joshi",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "  Suryansh barnwal",
    },
    {
      id:11,
      profilePicture: "assets/person/11.jpeg",
      username: "  Kishan barnwal",
    },
    {
      id:12,
      profilePicture: "assets/person/12.jpeg",
      username: "  Sourabh chauhan",
    },
    {
      id:13,
      profilePicture: "assets/person/13.jpeg",
      username: "  Ritesh Gupta",
    },
    {
      id:14,
      profilePicture: "assets/person/14.jpeg",
      username: "  Piryanshu Rohila",
    },
    {
      id:15,
      profilePicture: "assets/person/15.jpeg",
      username: "  Utkarsha Gupta",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 109,
      comment: 10,
    },
    {
      id: 11,
      desc: "“Remember that happiness is a way of travel – not a destination.”",
      photo: "assets/post/11.jpeg",
      date: "1 month ago",
      userId: 11,
      like: 39,
      comment: 18,
    },
    {
      id: 12,
      desc: "“Just because you're awake doesn't mean you should stop dreaming.”",
      photo: "assets/post/12.jpeg",
      date: "2 week ago",
      userId: 12,
      like: 54,
      comment: 15,
    },
    {
      id: 13,
      desc: "“Be yourself, there's no one better.”",
      photo: "assets/post/13.jpeg",
      date: "3 day ago",
      userId: 13,
      like: 43,
      comment: 7,
    },
    {
      id: 14,
      desc: "“Stress less and enjoy the best.”",
      photo: "assets/post/14.jpeg",
      date: "2 hour ago",
      userId: 14,
      like: 67,
      comment: 25,
    },
    {
      id: 15,
      desc: "“The way you speak to yourself matters the most.”",
      photo: "assets/post/15.jpeg",
      date: "50 mins ago",
      userId: 15,
      like: 36,
      comment: 17,
    },
  ];
  